Create 160-IntersectionOfTwoLinkedLists.java
webcordate/leet_code pull request #16
Opened 2019-03-11 11:36 UTC by tahahadayat

2019-03-22 14:40 UTC, touqeer-ahmad requested changes
What is the time complexity for this solution?

2019-03-22 14:40 UTC, touqeer-ahmad commented on Java/160-IntersectionOfTwoLinkedLists.java
> +			return null;
You 2 while loops........this ‘’if’ should never stasify.... right?

2019-03-22 15:39 UTC, tahahadayat commented
> What is the time complexity for this solution?
O(n) 😄

2019-08-10 15:14 UTC, touqeer-ahmad approved these changes

2019-08-10 15:14 UTC, merged